### ISSUE TITLE
稀にキーが押しっぱなし状態になります。

### ISSUE THREAD

**Issue by zakuri** [53175ddd/HT-Keys#19]
コミケで購入した物なのですが、その時はありがとうございました。
その後無事に完成しました。
完成後、稀にキーが押しっぱなし状態になります。(Ctrl+cとか、oとか)
シリコングリスでグリスアップしたのですが、不具合が解消されませんでした。

再現方法は、判らないです。感覚としては激しく押していると出てくる可能性が高いです。

この不具合について、解消する方法はありますか？

**Comment by zakuri** [comment]
返信ありがとうございます。

初めての自作キーボードだったので、完成して動いた時は感動しました。
使用した軸は、茶軸にしました。
始めは少し動きに違和感があったので、シリコンスプレーですべての軸をグリスアップしました。
その後、異次元のスコスコ感があって、元のキーボードに戻るのが辛いです。
出来れば作成したキーボードを使いたいと思っています。

不具合について、感覚的にCTRL+C等の同時押しから、違うキーに移動すると、そのまま状態が残っているような印象を受けました。

修正期待して、待っています。

**Comment by Riku-mc** [comment]
お待たせいたしました。完全な検証はまだできていませんが、ファームウェアのアップデート版が完成したためリリースいたしました。ご確認いただければと思います

https://github.com/Riku-mc/HT-Keys/releases/tag/v2.0-stable

**Comment by zakuri** [comment]
対応ありがとうございます。無事にインストールしました。今のところ問題ないです。
今後使ってみて、問題があったら報告します。

**Comment by 53175ddd** [comment]
諸事情によりアカウントが変わりましたので新しいアカウントからご連絡申し上げます

1 週間ほど経過いたしましたが、使用感のほどは如何でしょうか
問題点等ございましたらお教えいただければと思います

**Comment by zakuri** [comment]
連絡ありがとうございます。
その後、問題なく動作しています。今はメインキーボードとして活躍しています。

問題が発生している時は、既製品（FILCO Majestouch 2SC）の茶軸のキーボードを買って使っていたのですが、
同じ茶軸でも自作キーボードの方が、軽く、打ち心地が良かったので、
自作キーボードをメインにすることにしました。

既製品（FILCO Majestouch 2SC）も、シリコンスプレーでグリスアップしたのですが、
何故か、自作キーボードの方が打ち心地が良いです。
原因は分かりません。

同じ茶軸でも遊舎工房が出している物と違うのかもしれません。
また、キーキャップも影響されているのかなとも思っています。

とにかくキーボードのキーが軽くなって、体の負担が軽くなり良かったです。
今回の自作キーボードを提供して頂い、ありがとうございました。
コミケで良い出会いがあったと思っています。
不具合が発生したら、連絡します。

**Comment by 53175ddd** [comment]
気に入っていただけたようで何よりです。開発者冥利に尽きます
不具合やファームウェアの仕様変更依頼等ございましたらまたご連絡ください
不具合や問題点は Issue にて、仕様変更依頼等は PR や Twitter の DM にてお寄せください

今後とも HT-Keys-TKL をどうぞよろしくお願いいたします
